spring:
  application:
    name: backend-challenge
  jackson:
    time-zone: America/Sao_Paulo
  datasource:
    url: jdbc:postgresql://localhost:5432/backend-challenge
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8081

logging:
  level:
    root: INFO
    org:
      springframework:
        web: info
        boot:
          autoconfigure:
            security:
              servlet:
                UserDetailsServiceAutoConfiguration: off
      hibernate: ERROR

jwt:
  keys:
    private: ${JWT_PRIVATE_PEM}
    public: ${JWT_PUBLIC_PEM}